{% set name = "pytask" %}
{% set version = "0.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-{{ version }}.tar.gz
  sha256: 6f36564af275a6af46a7d62e7efeba8757504f7dd469457c835749f983a84a28

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - toml
  run:
    - attrs >=19.2.0
    - click
    - click-default-group
    - networkx >=2.4
    - packaging
    - pluggy
    - pony >=0.7.15
    - python >=3.7
    - rich
    - typing-extensions

test:
  requires:
    - pip
  imports:
    - pytask
    - _pytask
  commands:
    - pip check

    - pytask --help
    - pytask --version
    - pytask clean
    - pytask markers
    - pytask collect

about:
  home: https://github.com/pytask-dev/pytask
  license: MIT
  license_file: LICENSE
  summary: In its highest aspirations, pytask tries to be pytest as a build system.
  description: |
    pytask’s main purpose is to facilitate reproducible research by automating workflows
    in research projects.
  doc_url: https://pytask-dev.readthedocs.io/en/latest
  dev_url: https://github.com/pytask-dev/pytask/

extra:
  recipe-maintainers:
    - tobiasraabe
