{% set name = "pytask" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-{{ version }}.tar.gz
  sha256: 7e55faf6f507d094232ea384281db874d7f34d5f79bc4b595c89850fbf097b8c

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - attrs >=17.4.0
    - click
    - click-default-group
    - colorama  # [win]
    - networkx >=2.4
    - packaging
    - pluggy
    - pony >=0.7.13
    - python
    - rich

test:
  requires:
    - pip
  imports:
    - pytask
    - _pytask
  commands:
    - pip check

    - pytask --help
    - pytask --version
    - pytask clean
    - pytask markers
    - pytask collect

about:
  home: https://github.com/pytask-dev/pytask
  license: MIT
  license_file: LICENSE
  summary: In its highest aspirations, pytask tries to be pytest as a build system.
  description: |
    pytask’s main purpose is to facilitate reproducible research by automating workflows
    in research projects.
  doc_url: https://pytask-dev.readthedocs.io/en/latest
  dev_url: https://github.com/pytask-dev/pytask/

extra:
  recipe-maintainers:
    - tobiasraabe
