{% set name = "pytask" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask-{{ version }}.tar.gz
  sha256: 8f2b0c3390c7c75ae453a6bf435c9abecf538337eafc26f56eb5b95d1318befb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=21.3.0
    - click >=8.1.8,!=8.2.0
    - click-default-group >=1.2.4
    - networkx >=2.4.0
    - optree >=0.9.0
    - packaging >=23.0.0
    - pluggy >=1.3.0
    - python >={{ python_min }}
    - rich >=13.8.0
    - tomli >=1.0.0
    - typing-extensions >=4.8.0
    - sqlalchemy >=2.0.31
    - universal_pathlib >=0.2.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pytask
    - _pytask
  commands:
    - pip check

    - pytask --help
    - pytask --version
    - pytask clean
    - pytask collect
    - pytask markers
    - pytask profile

about:
  home: https://github.com/pytask-dev/pytask
  license: MIT
  license_file: LICENSE
  summary: pytask is a workflow management system that facilitates reproducible data analyses.
  doc_url: https://pytask-dev.readthedocs.io/en/stable
  dev_url: https://github.com/pytask-dev/pytask/

extra:
  recipe-maintainers:
    - tobiasraabe
