{% set name = "pytask" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask-{{ version }}.tar.gz
  sha256: 77da6f14081517b9ed0806bc9ff00f352f9f8daa637b59a88afaaf9174abeddb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=21.3.0
    - click >=7.0.0,!=8.2.0
    - click-default-group
    - networkx >=2.4
    - optree >=0.9
    - packaging
    - pluggy >=1.3.0
    - python >={{ python_min }}
    - rich
    - tomli >=1.0.0
    - typing-extensions
    - sqlalchemy >=2
    - universal_pathlib >=0.2.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pytask
    - _pytask
  commands:
    - pip check

    - pytask --help
    - pytask --version
    - pytask clean
    - pytask collect
    - pytask markers
    - pytask profile

about:
  home: https://github.com/pytask-dev/pytask
  license: MIT
  license_file: LICENSE
  summary: pytask is a workflow management system that facilitates reproducible data analyses.
  doc_url: https://pytask-dev.readthedocs.io/en/stable
  dev_url: https://github.com/pytask-dev/pytask/

extra:
  recipe-maintainers:
    - tobiasraabe
