{% set name = "pytask" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-{{ version }}.tar.gz
  sha256: c64bd66075b7b92184bddc841a5437bcf60f4f2a7e1b077db8313a94f9230869

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytask = _pytask.cli:cli

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - toml
  run:
    - attrs >=21.3.0
    - click
    - click-default-group
    - networkx >=2.4
    - optree >=0.9
    - pluggy >=1.0.0
    - python >=3.8
    - rich
    - sqlalchemy >=1.4.36
    - tomli >=1.0.0
    - typing_extensions

test:
  requires:
    - pip
  imports:
    - pytask
    - _pytask
  commands:
    - pip check

    - pytask --help
    - pytask --version
    - pytask clean
    - pytask collect
    - pytask markers
    - pytask profile

about:
  home: https://github.com/pytask-dev/pytask
  license: MIT
  license_file: LICENSE
  summary: pytask is a workflow management system which facilitates reproducible data analyses.
  doc_url: https://pytask-dev.readthedocs.io/en/stable
  dev_url: https://github.com/pytask-dev/pytask/

extra:
  recipe-maintainers:
    - tobiasraabe
